# 재귀 함수
> `recursion`, 반복 또는 되풀이를 의미

* 함수 정의 도중에 같은 이름의 함수가 나오는 경우
	* 함수를 호출하면 자기 자신을 계속 호출

#### 팩토리얼
> 어떤 수의 계승 1부터 어떤 수까지의 곱

* 3의 계승 == 3 X 2 X 1
	* `3!`로 나타냄
	* `3팩토리얼`이라고 읽음 

```
1| n! = (n - 1)! * n
	> 3! = 2! x n
2| n = 0 or 1 이면 n! = 1
```

1번 성질을 이용한 재귀 함수

```
def factorial(n):
	return factorial(n - 1) * n

if __name__ == '__main__':
	n = 3
	res = factorial(n)
	print('The factorial of {} is {}'.format(n, res))

==== 실행결과
RecursionError
```
* 오류가 발생하는 이유
	* 재귀 함수가 계속해서 자기 자신을 호출하기 때문
	* 스택 프레임이 계속생성 됨
	* 스택 오버플로 발생
* 오류를 막기위해선 `탈출 조건`이 필요함
	* 함수 호출을 멈추는 조건
* 팩토리얼에서의 탈출 조건
	* n = 0 or 1


##### 탈출 조건 추가
```
def factorial(n):
	if n <= 1:
		return 1
	return factorial(n - 1) * n

if __name__ == '__main__':
	n = 3
	res = factorial(n)
	print('The factorial of {} is {}'.format(n, res))

```

##### 피보나치 수

```
def fibonacch(n):
    if n == 1:
        return 0
    if n == 2:
        return 1
    return fibonacch(n-2) + fibonacch(n-1)
    
if __name__ == '__main__':
	n = 10
	for i in range(1, n+1):
		print(fibonacch(i), end = ' ')
		
==== 실행 결과
0 1 1 2 3 5 8 13 21 34 
```
 